#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).parents[2]
WORKFLOW_DIR = ROOT / ".github" / "workflows"
OUTPUT = ROOT / "docs" / "workflow-architecture.md"
JOB_PATTERN = re.compile(r"(?m)^  ([A-Za-z0-9_-]+):\s*$")
CALL_PATTERN = re.compile(r"uses: \./\.github/workflows/([^\s]+)")


def workflow_inventory() -> str:
    rows = []
    for path in sorted(WORKFLOW_DIR.glob("codex-*.yml")):
        content = path.read_text(encoding="utf-8")
        name = next(
            (line.removeprefix("name: ") for line in content.splitlines() if line.startswith("name: ")),
            path.name,
        )
        jobs = [job for job in JOB_PATTERN.findall(content) if job != "workflow_call"]
        calls = sorted(set(CALL_PATTERN.findall(content)))
        role = "Public entry point" if path.name in {
            "codex-implement.yml",
            "codex-review-feedback.yml",
        } else "Internal reusable stage"
        rows.append(
            f"| `{path.name}` | {name} | {role} | {len(jobs)} | "
            f"{', '.join(f'`{call}`' for call in calls) or '-'} |"
        )
    return "\n".join(rows)


def render() -> str:
    return f"""<!-- Generated by .github/scripts/generate-workflow-docs.py. Do not edit directly. -->
# Workflow architecture

The two public reusable workflows remain stable entry points. They delegate to explicitly permissioned stages from the same immutable caller release and transfer model output through artifacts into fresh trusted jobs.

## Jira-to-PR implementation

```mermaid
flowchart LR
    Jira[Jira dispatch] --> Plan[Read-only planning]
    Plan --> Validate[Trusted plan validation]
    Validate --> Generate[Implementation model]
    Generate --> Collect[Trusted patch collection]
    Collect --> Verify[Credential-free verification]
    Verify -->|failed| Repair[Repair model round]
    Repair --> Collect
    Verify -->|passed| Publish[GitHub App publication]
    Verify -->|repairs exhausted| Draft[Draft PR with evidence]
    Publish --> Checks[Jenkins, Sonar and required checks]
    Checks -->|failed| PostRepair[Post-publication repair]
    Checks -->|passed| Ready[Ready PR and Jira callback]
```

## Security boundaries

```mermaid
flowchart TB
    subgraph Model[Model-facing job]
      Prepare[Trusted prompt preparation] --> Codex[Codex Action as final step]
    end
    Codex -->|structured output| Artifact[(Short-lived artifact)]
    subgraph Trusted[Fresh trusted jobs]
      Artifact --> Collector[Patch collector]
      Collector --> Verification[Credential-free verification]
      Verification --> Safety[Dual-tree workflow safety gate]
      Safety --> Token[Mint scoped GitHub App token]
      Token --> Publisher[Publish or update PR]
    end
    Secrets[OpenAI credential] --> Codex
    App[GitHub App credential] --> Token
    App -. unavailable .-> Model
```

## PR feedback

```mermaid
flowchart LR
    Comment[Trusted /codex-review comment] --> Intake[Validate actor and PR]
    Intake --> Feedback[Collect review feedback]
    Feedback --> Model[Review repair model]
    Model --> Artifact[(Structured patch artifact)]
    Artifact --> Verify[Credential-free verification]
    Verify --> Publish[GitHub App update]
    Publish --> Status[Required checks and Jira callback]
```

## Generated component inventory

| Workflow | Name | Role | Jobs | Calls |
|---|---|---|---:|---|
{workflow_inventory()}

`codex-post-repair.yml` is intentionally retained as one component even though it is slightly above the nominal 700-line target. Its model, trusted collection, credential-free verification, publication and terminal handling remain separate jobs; splitting it further would add another nested reusable-workflow level to a security-sensitive recovery path.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate workflow architecture documentation")
    parser.add_argument("--check", action="store_true", help="fail when generated documentation is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).relative_to(ROOT)}")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
